# Generated by Django 5.1.1 on 2024-09-20 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_detail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detail',
            old_name='request',
            new_name='request_guests',
        ),
    ]
