# Generated by Django 5.1.1 on 2024-09-24 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_rewiew'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rewiew',
            name='rating',
            field=models.FloatField(choices=[('5 - Excellent', '5 - Excellent'), ('4 - Good', '4 - Good'), ('3 - Average', '3 - Average'), ('2 - Poor', '2 - Poor'), ('1 - Terrible', '1 - Terrible')]),
        ),
    ]
