# Generated by Django 5.1.1 on 2024-09-24 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_alter_rewiew_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rewiew',
            name='rating',
            field=models.FloatField(choices=[('Excellent', 'Excellent'), ('Good', 'Good'), ('Average', 'Average'), ('Poor', 'Poor'), ('Terrible', 'Terrible')]),
        ),
    ]
