# Generated by Django 5.1.1 on 2024-09-24 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_alter_rewiew_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rewiew',
            name='short_discription',
            field=models.TextField(),
        ),
    ]
